FROM node:20-alpine3.20 AS build
WORKDIR /usr/src/app
COPY client/package*.json ./
RUN npm ci
COPY ./client ./
RUN npm run build

FROM nginx:stable-alpine AS prod
# COPY --from=build /usr/src/app/nginx /etc/nginx/conf.d
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"] 