apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchenette-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kitchenette-client
  template:
    metadata:
      labels:
        app: kitchenette-client
    spec:
      containers:
        - name: kitchenette-client
          image: amitazoulay1611/the-kitchenette-client:latest
          ports:
            - containerPort: 80
          env:
          - name: MONGO_URL
            value: mongodb+srv://amitazoulay1611:SU6sZpTEJ8cmGZB8@cluster0.rarblbz.mongodb.net/kitchenette
          - name: REACT_APP_KHASH
            value: $2b$10$tf99h3B3lhG7j61R0CYHee"
          - name: REACT_APP_ZHASH
            value: tf99h3B3lhG7j61R0CYHee
          - name: REACT_APP_REACT_URL
            value: http://localhost:3000
          - name: REACT_APP_JWT_SECRET
            value: U!n&JJ&iPC-Uwq8zyTu@J*acc!BG$3Ie@S0lvoUa8ye0Syxdro
          - name: REACT_APP_SERVER_URL
            value: http://kitchenette-server-service:4000
---
apiVersion: v1
kind: Service
metadata:
  name: kitchenette-client-service
spec:
  selector:
    app: kitchenette-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
