# service.yaml

apiVersion: v1
kind: Service
metadata:
  name: kitchenette-backend-service
spec:
  type: NodePort
  selector:
    app: kitchenette-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30001
