apiVersion: apps/v1
kind: Deployment
metadata:
  name: kitchenette-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kitchenette-backend
  template:
    metadata:
      labels:
        app: kitchenette-backend
    spec:
      containers:
        - name: kitchenette-backend
          image: amitazoulay1611/the-kitchenette-server
          ports:
            - containerPort: 4000
          resources:
            requests:
              memory: "256Mi" # Request 256 MB of memory
            limits:
              memory: "512Mi" # Limit to 512 MB of memory
          env:
          - name: MONGO_URL
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: mongo-url
